operation/client/urls.py
from django.urls import path
from .views import HomeClientView, ClientListView, ClientDetailView


app_name = 'client'

urlpatterns = [
    path('list/', HomeClientView.as_view(), name='client-list'),
    path('clients_json/', ClientListView.as_view(), name='client-json'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    # path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),   

]

operation/deal/urls.py
from django.urls import path
from .views import HomeDealView, DealListView, DealDetailView, DealUpdateView, DealDeleteView, DealHomeTaskView, DealTaskListView, DealTaskDetailView, DealTaskUpdateView, DealTaskDeleteView, DealTaskCreateView

app_name = 'deal'

urlpatterns = [
    path('list/', HomeDealView.as_view(), name='list'),
    path('deals_json/', DealListView.as_view(), name='deal-json'),
    # path('create/', DealCreateView.as_view(), name='create'),
    path('<int:pk>/', DealDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', DealUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', DealDeleteView.as_view(), name='delete'),

    path('task/list/', DealHomeTaskView.as_view(), name='task-list'),
    path('tasks_json/', DealTaskListView.as_view(), name='task-json'),
    path('<int:deal_pk>/task/create/', DealTaskCreateView.as_view(), name='task-create'),
    path('task/<int:pk>/', DealTaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update/', DealTaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', DealTaskDeleteView.as_view(), name='task-delete'),
]

operation/lead/urls.py
from django.urls import path
from .views import HomeLeadView, LeadListView, LeadCreateView, LeadUpdateView, LeadDetailView, LeadDeleteView, LeadTaskCreateView, LeadHomeTaskView, LeadTaskListView, LeadTaskDetailView, LeadTaskDeleteView, LeadTaskUpdateView, convert_lead_to_deal

app_name = 'lead'

urlpatterns = [
    path('list/', HomeLeadView.as_view(), name='list'),
    path('leads_json/', LeadListView.as_view(), name='lead-json'),
    path('create/', LeadCreateView.as_view(), name='create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='delete'),
    path('converted_to_deal/<int:pk>/', convert_lead_to_deal, name='converted-to-deal'),


    path('task/list/', LeadHomeTaskView.as_view(), name='task-list'),
    path('tasks_json/', LeadTaskListView.as_view(), name='task-json'),
    path('<int:lead_pk>/task/create/', LeadTaskCreateView.as_view(), name='task-create'),
    path('task/<int:pk>/', LeadTaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update/', LeadTaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', LeadTaskDeleteView.as_view(), name='task-delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('administration.core.urls')),
    path('<slug:organization_slug>/media/', include('administration.organization.urls')),
    path('', include('operation.dashboard.urls')),
    path('<slug:organization_slug>/dashboard/', include('operation.dashboard.urls')),

    path('<slug:organization_slug>/configuration/country/', include('configuration.country.urls')),
    path('<slug:organization_slug>/configuration/currency/', include('configuration.currency.urls')),

    path('<slug:organization_slug>/lead/', include('operation.lead.urls')),
    path('<slug:organization_slug>/deal/', include('operation.deal.urls')),
    path('<slug:organization_slug>/contact/', include('operation.contact.urls')),
    path('<slug:organization_slug>/company/', include('operation.company.urls')),
    path('<slug:organization_slug>/client/', include('operation.client.urls')),
    path('<slug:organization_slug>/product/', include('configuration.product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

operation/client/models.py
from django.db import models
from django.contrib.auth.models import User

from configuration.country.models import Country
from administration.organization.models import Organization
from operation.company.models import Company


def get_sentinel_user():
    user, created = User.objects.get_or_create(username="deleted")
    if created:
        user.set_unusable_password()
        user.save()
    return user

class Client(models.Model):
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    TITLE_CHOICES = [
        ('ceo', 'CEO'),
        ('company_rep', 'Company Representative'),
        ('independent_professional', 'Independent Professional'),
        ('entrepreneur', 'Entrepreneur'),
        ('student', 'Student'),
    ]
    title = models.CharField(max_length=50, choices=TITLE_CHOICES)
    primary_email = models.EmailField(unique=True, blank=False)
    phone = models.CharField(max_length=20, blank=True)
    mobile_phone = models.CharField(max_length=20, blank=True)
    company = models.ForeignKey(Company, on_delete=models.SET_NULL, null=True, related_name='clients_company')
    country = models.ForeignKey(
            Country, on_delete=models.SET_NULL, blank=False, null=True, limit_choices_to={'is_selected': True})
    created_by = models.ForeignKey(User, related_name='created_client', on_delete=models.SET(get_sentinel_user))
    last_modified_by = models.ForeignKey(User, related_name='last_modified_client', on_delete=models.SET(get_sentinel_user))
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    organization = models.ForeignKey(Organization, related_name='client_organization', on_delete=models.CASCADE)  
    erased = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()

    def __str__(self):
        return self.first_name + " " + self.last_name

operation/company/models.py
from django.db import models
from django.contrib.auth.models import User

from configuration.country.models import Country
from administration.organization.models import Organization


def get_sentinel_user():
    user, created = User.objects.get_or_create(username="deleted")
    if created:
        user.set_unusable_password()
        user.save()
    return user


class Company(models.Model):    
    company_name = models.CharField(max_length=255)
    company_email = models.EmailField(blank=False)
    company_phone = models.CharField(max_length=20, blank=True)
    website = models.URLField(blank=True)
    INDUSTRY_CHOICES = [
        ('public', 'Public'),
        ('private', 'Private'),
        ('non_profit', 'Non-Profit'),
    ]
    industry = models.CharField(max_length=20, choices=INDUSTRY_CHOICES)    
    created_by = models.ForeignKey(User, related_name='created_company', on_delete=models.SET(get_sentinel_user))
    last_modified_by = models.ForeignKey(User, related_name='last_modified_company', on_delete=models.SET(get_sentinel_user))
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)    
    organization = models.ForeignKey(Organization, related_name='organization_company', on_delete=models.CASCADE)      
    erased = models.BooleanField(default=False)
    is_client = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.company_name = self.company_name.title()

    def __str__(self):       
        return self.company_name  
    
    def save(self, *args, **kwargs):
        if self.website:
            if self.website.startswith('http://'):
                # Reemplazar http:// por https://
                self.website = 'https://' + self.website[len('http://'):]
            elif not self.website.startswith('https://'):
                # Añadir https:// si no comienza con http:// o https://
                self.website = 'https://' + self.website

        if self.website and not self.website.startswith('https://'):
            self.website = 'https://' + self.website
        super().save(*args, **kwargs)

operation/dashboard/models.py
from django.db import models

# Create your models here.

operation/deal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.validators import MaxLengthValidator

from configuration.country.models import Country
from administration.organization.models import Organization
from configuration.currency.models import Currency
from configuration.product.models import Product
from operation.company.models import Company
from operation.client.models import Client


def get_sentinel_user():
    user, created = User.objects.get_or_create(username="deleted")
    if created:
        user.set_unusable_password()
        user.save()
    return user


class Deal(models.Model):
    deal_name = models.CharField(max_length=100, unique=True, blank=False, null=True)
    DEAL_SOURCE_CHOICES = [
        ('website', 'Website'),
        ('whatsapp', 'Whatsapp'),
        ('direct_mail', 'Direct Mail'),
        ('phone_call', 'Phone Call'),
        ('in_person', 'In Person'),
        ('social_media', 'Social Media'),
    ]
    deal_source = models.CharField(max_length=50, choices=DEAL_SOURCE_CHOICES)

    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True, related_name='client_deals')
    primary_email = models.EmailField(blank=False)
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    TITLE_CHOICES = [
        ('ceo', 'CEO'),
        ('company_rep', 'Company Representative'),
        ('independent_professional', 'Independent Professional'),
        ('entrepreneur', 'Entrepreneur'),
        ('student', 'Student'),
    ]
    title = models.CharField(max_length=50, choices=TITLE_CHOICES)
    phone = models.CharField(max_length=20, blank=True)
    mobile_phone = models.CharField(max_length=20, blank=True)

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_deals', null=True, blank=True)
    company_name = models.CharField(max_length=255)
    company_email = models.EmailField(blank=False)
    company_phone = models.CharField(max_length=20, blank=True)
    website = models.URLField(blank=True)
    INDUSTRY_CHOICES = [
        ('public', 'Public'),
        ('private', 'Private'),
        ('non_profit', 'Non-Profit'),
    ]
    industry = models.CharField(max_length=20, choices=INDUSTRY_CHOICES)

    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, blank=False, null=True, limit_choices_to={'is_selected': True})
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)  

    description = models.TextField(validators=[MaxLengthValidator(280)])

    assigned_to = models.ForeignKey(User, related_name='assigned_deal', on_delete=models.SET(get_sentinel_user))
    created_by = models.ForeignKey(User, related_name='created_deal', on_delete=models.SET(get_sentinel_user))
    last_modified_by = models.ForeignKey(User, related_name='last_modified_deal', on_delete=models.SET(get_sentinel_user))

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    start_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    end_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    extended_end_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")    
    actual_completion_date = models.DateTimeField(null=True, blank=True)
    
    organization = models.ForeignKey(Organization, related_name='deal', on_delete=models.CASCADE)    
    
    STAGE_CHOICES = [
        ('new', 'New'),
        ('in_progress', 'In Progress'),
        ('dorman', 'Dorman'),
        ('close_win', 'Close Win'),
        ('close_lost', 'Close Lost'),
    ]
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='new')
    is_closed = models.BooleanField(default=False)  
    erased = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.deal_name = self.deal_name.title()
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()

    def __str__(self):
        return self.deal_name
    
    def save(self, *args, **kwargs):
        if self.website:
            if self.website.startswith('http://'):
                # Reemplazar http:// por https://
                self.website = 'https://' + self.website[len('http://'):]
            elif not self.website.startswith('https://'):
                # Añadir https:// si no comienza con http:// o https://
                self.website = 'https://' + self.website

        if self.website and not self.website.startswith('https://'):
            self.website = 'https://' + self.website
        super().save(*args, **kwargs)


class DealProduct(models.Model):
    deal = models.ForeignKey(
        Deal, related_name='deal_product', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='deal_product', on_delete=models.CASCADE)
    cotizacion_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.product.name


class DealTask(models.Model):
    name = models.CharField(max_length=200, blank=False)
    deal = models.ForeignKey('Deal', related_name='deal_dealtask', on_delete=models.CASCADE, null=True, blank=True)
    deal_product = models.ForeignKey('DealProduct', related_name='product_dealtask', on_delete=models.CASCADE, null=True, blank=True)
    parent_task = models.ForeignKey('self', null=True, blank=True, related_name='parent_dealtask', on_delete=models.CASCADE)
    description = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='created_dealtask', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='assigned_dealtask', on_delete=models.CASCADE)
    last_modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modified_dealtask', on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, related_name='organization_dealtask', on_delete=models.CASCADE)
    STAGE_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
    ]   
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='pending')    
    is_closed = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.name = self.name.title()

    def __str__(self):
        return self.name

operation/dashboard/forms.py
from django import forms

from administration.organization.models import OrganizationMedia

class ImageSelectionForm(forms.Form):
    image = forms.ModelChoiceField(queryset=OrganizationMedia.objects.all(), empty_label=None)

operation/dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from administration.organization.models import Organization, OrganizationMedia

@login_required
def dashboard(request, organization_slug=None):
    context = {'title': 'Dashboard'}
        # Obtén todas las imágenes de la biblioteca de medios
    media_list = OrganizationMedia.objects.all()
    # Pasa las URLs de las imágenes al contexto
    context = {'media_urls': [media.image.url for media in media_list]}
    return render(request, 'operation/dashboard/dashboard_home.html', context)


from django.shortcuts import render
from .forms import ImageSelectionForm

def select_image_view(request):
    if request.method == 'POST':
        form = ImageSelectionForm(request.POST)
        if form.is_valid():
            selected_image = form.cleaned_data['image']
            # Realiza cualquier acción necesaria con la imagen seleccionada
            # Por ejemplo, puedes mostrarla en otra parte de la aplicación o guardar su URL en la base de datos
            return render(request, 'otra_plantilla.html', {'selected_image': selected_image})
    else:
        form = ImageSelectionForm()
    
    return render(request, 'tu_plantilla.html', {'form': form})

templates/operation/lead/lead_delete.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %}Delete Lead{% endblock %}

{% block content %}

    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 mx-auto my-5">
        <div class="card">
            <h5 class="card-header">{{ lead.lead_name }}</h5>
            <div class="card-body">
                <h5 class="card-title">Are you sure you want to delete {{ lead.first_name }} {{ lead.last_name }}?</h5>
                <br>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/operation/lead/lead_detail.html
{% extends "administration/core/base.html" %}

{% block title %}{% endblock %}

{% block content %}

<div class="card" style="width: 42rem;">
    <div class="card-header">
        <h2>{{ lead.lead_name }}</h2>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ lead.lead_source }} <span class="badge bg-secondary">Lead Source</span></li>
        <li class="list-group-item">{{ lead.first_name }} {{ lead.last_name }}</li>
        <li class="list-group-item">{{ lead.primary_email }}  
        <li class="list-group-item">{{ lead.website }} <span class="badge bg-secondary">Webpage</span></li>
        <li class="list-group-item">{{ lead.phone }} <span class="badge bg-secondary">Phone</span></li>
        <li class="list-group-item">{{ lead.mobile_phone }} <span class="badge bg-secondary">Cellphone</span></li>
        <li class="list-group-item">{{ lead.country }} <span class="badge bg-secondary">Country</span></li>
        <li class="list-group-item">{{ lead.assigned_to }} <span class="badge bg-secondary">Assigned to</span></li>
        <li class="list-group-item">{{ lead.created_by }} <span class="badge bg-secondary">Created By</span></li>
        <li class="list-group-item">{{ lead.created_time }} <span class="badge bg-secondary">Created</span></li>
        <li class="list-group-item">{{ lead.start_date_time }} <span class="badge bg-secondary">Start</span></li>
        <li class="list-group-item">{{ lead.end_date_time }} <span class="badge bg-secondary">End</span></li>
        <li class="list-group-item">{{ lead.extended_end_date_time }} <span class="badge bg-info">Extended End</span></li>        
        {% for lead_product in lead_products %}
            <li class="list-group-item">Product: {{ lead_product.product.name }} - Category: {{ lead_product.product.category.name }} - Product URL: {{ lead_product.product.url }} - Cotización URL: {{ lead_product.cotizacion_url }}</li>
        {% empty %}
            <li class="list-group-item">No products associated with this lead.</li>
        {% endfor %}
            
        {% for lead_task in lead_tasks %}
            <li class="list-group-item"> Tareas: <a href="{% url 'lead:task-detail' pk=lead_task.id organization_slug=organization_slug %}">{{ lead_task.name }}</a> </li>  
        {% empty %}
            <li class="list-group-item">No tasks associated with this lead.</li>
        {% endfor %}
        <li class="list-group-item">{{ lead.stage }}   <span class="badge bg-success">Stage</span></li>
    </ul>
</div>
<div class="col-md-8 mt-3">
    <a href="{% url 'lead:update' pk=lead.pk organization_slug=organization_slug %}" class="btn btn-primary">Update</a>
    <a href="{% url 'lead:delete' pk=lead.pk organization_slug=organization_slug %}" class="btn btn-danger">Delete</a>
</div>
                

{% endblock %}

templates/operation/lead/lead_update.html
{% extends "administration/core/base.html" %}

{% block title %} {{ titulo }} {% endblock %}

{% block content %}

<div class="container rounded shadow-sm bg-light border border-2 p-5 my-4" >

    <form action="." method="post" class="">
        {% csrf_token %}
        <div class="row mb-3">
            <div class="col-md-9">
                <label for="id_lead_name" class="form-label">Lead Nombre</label>
                {{ form.lead_name }}
            </div>
            <!-- Campo de Lead Source -->
            <div class="col-md-3">
                <label for="id_lead_source" class="form-label">Lead Source</label>
                {{ form.lead_source }}
            </div>
        </div>


        <div class="row mb-3">
            <div class="col-md-5">
                <label for="id_first_name" class="form-label">Nombre</label>
                {{ form.first_name }}
            </div>
            <div class="col-md-4">
                <label for="id_last_name" class="form-label">Apellido</label>
                {{ form.last_name }}
            </div>
            <!-- Campo de Title -->
            <div class="col-md-3">
                <label for="id_title" class="form-label">Title</label>
                {{ form.title }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-8">
                <label for="addLeadUnregisterEmail" class="form-label">Email</label>
                {{ form.primary_email }}
                {% if form.errors.primary_email %}
                    <div class="text-danger">{{ form.errors.primary_email }}</div>
                {% endif %}
            </div>     
        </div>

        <!-- Campos de Phone y Mobile Phone -->
        <div class="row mb-3">
            <div class="col-md-5">
                <label for="id_phone" class="form-label">Phone</label>
                {{ form.phone }}
            </div>
            <div class="col-md-5">
                <label for="id_mobile_phone" class="form-label">Mobile Phone</label>
                {{ form.mobile_phone }}
            </div>
        </div>

        <!-- Campo de Company Name -->
        <div class="row mb-3">
            <div class="col-md-8">
                <label for="id_company_name" class="form-label">Company Name</label>
                {{ form.company_name }}
            </div>
            <div class="col-md-2">
                <label for="id_industry" class="form-label">Industry</label>
                {{ form.industry }}
            </div> 
        </div>

        <!-- Campo de Company Email -->
        <div class="row mb-3">
            <div class="col-md-7">
                <label for="id_company_email" class="form-label">Company Email</label>
                {{ form.company_email }}
            </div>
            <div class="col-md-3">
                <label for="id_company_phone" class="form-label">Company Phone</label>
                {{ form.company_phone }}
            </div>
        </div>

        <!-- Campo de Website -->
        <div class="row mb-3">
            <div class="col-md-8">
                <label for="id_website" class="form-label">Website</label>
                {{ form.website }}
                {% if form.errors.website %}
                    <div class="text-danger">{{ form.errors.website }}</div>
                {% endif %}
            </div>
        </div> 

        <div class="row mb-3">
            <div class="col-md-4">
                <label for="id_country" class="form-label">Country</label>
                {{ form.country }}
            </div>
            <div class="col-md-2">
                <label for="id_currency" class="form-label">Currency</label>
                {{ form.currency }}
            </div>  
        </div>


        <div class="row mb-3">
            <div class="col-md-12">
                <label for="id_description" class="form-label">Description</label>
                {{ form.description }}
            </div>
        </div>    

        <div class="row mb-3">
            <div class="col-md-4">
                <label for="id_start_date_time" class="form-label">Start Date</label>
                {{ form.start_date_time }}
            </div>
            <div class="col-md-4">
                <label for="id_end_date_time" class="form-label">End Date</label>
                {{ form.end_date_time }}
            </div>
            <div class="col-md-4" {% if hide_extended_end_date_time %}style="display:none;" {% endif %}>
                <label for="id_extended_end_date_time" class="form-label">Extended End Date</label>
                {{ form.extended_end_date_time }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-5">
                <label for="id_assigned_to" class="form-label">Assigned to</label>
                {{ form.assigned_to }}
            </div>
        </div>
        
        <div class="row mb-3">
            {{ formset.management_form }}
            <div id="form-list" class="col-md-5 alert alert-secondary" role="alert">
                {% for form in formset %}
                    <div class="deal-product-form">{{ form.as_p }}</div>
                {% endfor %}
                <button type="button" id="add-more-product" class="btn btn-primary" {% if not enable_button %}disabled{% endif %} {% if not enable_button %}onclick="return false;"{% endif %}>Add Product</button> {# Botón para añadir más formularios #}
            </div>
        </div>

        <!-- LeadProductForm oculto para crear uno nuevo con JS -->
        <span id="lead-info" data-stage="{{ lead.stage }}" data-is-closed="{{ lead.is_closed }}" style="display: none;"></span>
        <span id="form-index" data-form-index="{{ formset.total_form_count }}" style="display: none;"></span>
        <div id="form-template" style="display: none;">
            {{ formset.empty_form.as_p }}
        </div>
        
        <div class="row mb-3">
            <div class="col-md-5 alert bg-success-subtle" role="alert">
                <label for="formGroupExampleInput2" class="form-label">Stage</label>
                {{ form.stage }}
            </div>
        </div>

        <br>
                       
        <div class="row my-5">
            <div class="btn-group">
                <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                {% if lead %}
                    <a href="{% url 'lead:task-create' lead_pk=lead.id organization_slug=organization_slug %}" id="add-more-task"
                    class="btn btn-warning {% if not enable_button %}disabled{% endif %}" {% if not enable_button %}onclick="return false;" {% endif %}>Agregar Task</a>
                {% endif %}
                <button id="updateLeadFormButton" type="submit" class="btn btn-primary" {% if not enable_update %}disabled{% endif %} {% if not enable_update %}onclick="return false;"{% endif %}>Update</button>
            </div>
        </div>
    </form>



</div>


{% endblock %}


{% block scripts %}

<script>
    // Oculta botones segun el stage del Lead
    document.addEventListener('DOMContentLoaded', function () {
        var formIndex = document.getElementById('form-index').getAttribute('data-form-index');
        const addMoreProductButton = document.getElementById('add-more-product');
        const addMoreTaskButton = document.getElementById('add-more-task');
        const convertLeadToDealButton = document.getElementById('ConvertLeadToDeal');
        const updateFormButton = document.getElementById('updateLeadFormButton');
        const formListContainer = document.getElementById('form-list');
        const formTemplate = document.getElementById('form-template').innerHTML;

        // Leer los datos de stage y is_closed
        const leadInfo = document.getElementById('lead-info');
        const leadStage = leadInfo.getAttribute('data-stage');
        const leadIsClosed = leadInfo.getAttribute('data-is-closed') === 'True';

        // Ocultar el botón si el lead está cerrado o si el stage es 'close_win' o 'close_lost'
        if (leadIsClosed || leadStage === 'close_lost') {
            addMoreProductButton.style.display = 'none';
            addMoreTaskButton.style.display = 'none';
            convertLeadToDealButton.style.display = 'none';
            updateFormButton.style.display = 'none';

        } else {
            addMoreProductButton.addEventListener('click', function () {
            let newFormHtml = formTemplate.replace(/__prefix__/g, formIndex);
            formListContainer.insertAdjacentHTML('beforeend', newFormHtml);

            // Oculta o elimina el checkbox de eliminación en el nuevo formulario
            const newForm = formListContainer.lastElementChild;
            const deleteCheckbox = newForm.querySelector('input[type="checkbox"][name$="DELETE"]');
            const deleteLabel = deleteCheckbox ? deleteCheckbox.previousElementSibling : null;
            if (deleteCheckbox && deleteLabel) {
                    deleteCheckbox.style.display = 'none';
                    deleteLabel.style.display = 'none';
                }

                document.getElementById('id_lead_product-TOTAL_FORMS').value = ++formIndex;
            });
        }
    });
</script>



<script>
    // Encuentra todas las casillas de verificación de eliminación de producto y cambia el texto de la etiqueta
    document.addEventListener('DOMContentLoaded', function () {
        document.querySelectorAll('#form-list input[type="checkbox"][name$="DELETE"]').forEach(function (deleteCheckbox) {
            var deleteLabel = deleteCheckbox.previousElementSibling;
            if (deleteLabel) {
                deleteLabel.textContent = 'Delete Product';
            }
        });
    });
</script>

    
{% endblock %}