configuration/country/urls.py
from django.urls import path
from .views import CountryListView, CountryDetailView, CountryCreateView, CountryUpdateView, CountryDeleteView

app_name = 'country'

urlpatterns = [
    path('list/', CountryListView.as_view(), name='list'),
    path('create/', CountryCreateView.as_view(), name='create'),
    path('<int:pk>/', CountryDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', CountryUpdateView.as_view(), name='update'),    
    path('<int:pk>/delete/', CountryDeleteView.as_view(), name='delete'),
]

configuration/currency/urls.py
from django.urls import path
from .views import CurrencyListView, CurrencyDetailView, CurrencyCreateView, CurrencyUpdateView, CurrencyDeleteView

app_name = 'currency'

urlpatterns = [
    path('list/', CurrencyListView.as_view(), name='list'),
    path('create/', CurrencyCreateView.as_view(), name='create'),
    path('<int:pk>/', CurrencyDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', CurrencyUpdateView.as_view(), name='update'),    
    path('<int:pk>/delete/', CurrencyDeleteView.as_view(), name='delete'),
]

configuration/product/urls.py
from django.urls import path
from .views import (
    ProductListView, ProductCreateView, ProductDetailView, ProductUpdateView, ProductDeleteView, 
    ProductCategoryListView, ProductCategoryCreateView, ProductCategoryDetailView, ProductCategoryUpdateView, ProductCategoryDeleteView
)

app_name = 'product'


urlpatterns = [
    # Rutas para Product
    path('list/', ProductListView.as_view(), name='list'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', ProductUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', ProductDeleteView.as_view(), name='delete'),

    # Rutas para ProductCategory con prefijo 'category-'
    path('categories/list/', ProductCategoryListView.as_view(), name='category-list'),
    path('categories/create/', ProductCategoryCreateView.as_view(), name='category-create'),
    path('categories/<int:pk>/', ProductCategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', ProductCategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', ProductCategoryDeleteView.as_view(), name='category-delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('administration.core.urls')),
    path('<slug:organization_slug>/media/', include('administration.organization.urls')),
    path('', include('operation.dashboard.urls')),
    path('<slug:organization_slug>/dashboard/', include('operation.dashboard.urls')),

    path('<slug:organization_slug>/configuration/country/', include('configuration.country.urls')),
    path('<slug:organization_slug>/configuration/currency/', include('configuration.currency.urls')),

    path('<slug:organization_slug>/lead/', include('operation.lead.urls')),
    path('<slug:organization_slug>/deal/', include('operation.deal.urls')),
    path('<slug:organization_slug>/contact/', include('operation.contact.urls')),
    path('<slug:organization_slug>/company/', include('operation.company.urls')),
    path('<slug:organization_slug>/client/', include('operation.client.urls')),
    path('<slug:organization_slug>/product/', include('configuration.product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

configuration/country/models.py
from django.db import models
from django.core.validators import RegexValidator
from administration.organization.models import Organization

class Country(models.Model):
    name = models.CharField(max_length=100, null=False,
                            blank=False, help_text="Nombre del país")
    code = models.CharField(
        max_length=6,
        null=False,
        blank=False,
        validators=[
            RegexValidator(
                r'^CO[A-Z]{3}$', 'El código debe empezar con CO seguido de tres mayúsculas')
        ]
    )
    is_selected = models.BooleanField(
        default=False, help_text="Indica si el país está seleccionado")
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def clean(self):
        super().clean()
        self.name = self.name.title()
        self.code = self.code.upper()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'
        ordering = ['name']
        constraints = [
            models.CheckConstraint(
                check=models.Q(code__regex=r'^CO[A-Z]{3}$'),
                name='El código debe empezar con CO seguido de tres mayúsculas'
            ),
            models.UniqueConstraint(
                fields=['code', 'organization'],
                name='La combinación de código y organización debe ser única.'
            ),
            models.UniqueConstraint(
                fields=['name', 'organization'],
                name='La combinación de nombre y organización debe ser única.'
            ),
        ]


'''
Ventajas de usar validators directamente en el campo:
Validación más específica: Al colocar la validación directamente en el campo, estás asociando la validación específicamente con ese campo. Esto puede ser útil si la validación es intrínseca al campo y no se aplica a la relación entre varios campos.
Reutilización en formularios: Si también estás utilizando formularios en tu aplicación, definir la validación directamente en el campo puede permitir la reutilización de la misma validación en los formularios de Django.

Ventajas de usar CheckConstraint:
Validación a nivel de base de datos: Las restricciones de comprobación se aplican a nivel de base de datos, lo que garantiza que los datos cumplan con las reglas de validación incluso si se insertan directamente a través de consultas de base de datos sin pasar por la capa de aplicación.
Mayor flexibilidad para reglas complejas: Si la regla de validación implica la relación entre varios campos o es más compleja, puede tener más sentido usar una restricción de comprobación, ya que puede involucrar más de un campo o requerir una lógica más avanzada.

Se pueden usar las dos tipos de validacion para una validacion mas completa.
'''

configuration/currency/models.py
from django.db import models
from administration.organization.models import Organization


class Currency(models.Model):
    # Código ISO de la moneda, como 'USD', 'EUR', etc.
    # code = models.CharField(max_length=3)
    code = models.CharField(max_length=3, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def clean(self):
        super().clean()
        self.code = self.code.upper()

    def __str__(self):
        return self.code
    
    class Meta:
        verbose_name = 'Currency'
        verbose_name_plural = 'Currencies'
        ordering = ['code']

configuration/product/models.py
from django.db import models
from administration.organization.models import Organization


class ProductCategory(models.Model):
    name = models.CharField(max_length=200)
    url = models.URLField()
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    product_url = models.URLField(null=True, blank=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

configuration/country/forms.py
from django import forms

from .models import Country

class CountryForm(forms.ModelForm):
    name = forms.CharField(
        label="Country Name", 
        max_length=200, 
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Country Name'}
        )
    )
    code = forms.CharField(
        label="Country Code", 
        max_length=6, 
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Country Code'}
        )
    )
    is_selected = forms.BooleanField(
        label="Selected", 
        required=False,  # Permite que el campo esté vacío
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input'}
        )
    )

    class Meta:
        model = Country
        fields = ['name', 'code', 'is_selected']

configuration/currency/forms.py
from django import forms
from .models import Currency

class CurrencyForm(forms.ModelForm):
    code = forms.CharField(
        label="Currency Code", 
        max_length=3, 
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Currency Code'}
        ),
        error_messages={
            # 'unique': 'Este código ya está en uso. Por favor, proporciona un código diferente.',
            'invalid': 'Por favor, introduce un código válido.'
        }
    )
    class Meta:
        model = Currency
        fields = ['code']

configuration/product/forms.py
from django import forms
from .models import Product, ProductCategory


class ProductForm(forms.ModelForm):
    name = forms.CharField(max_length=200, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Product Name'}))
    category = forms.ModelChoiceField(queryset=ProductCategory.objects.all(), widget=forms.Select(attrs={'class': 'form-select'}))
    product_url = forms.CharField(max_length=200, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Product URL'}))

    class Meta:
        model = Product
        fields = ('name', 'category', 'product_url')

    def __init__(self, *args, **kwargs):
        organization = kwargs.pop('organization', None)
        super(ProductForm, self).__init__(*args, **kwargs)
        if organization:
            self.fields['category'].queryset = ProductCategory.objects.filter(organization=organization)



class ProductCategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=200, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Product Name'}))
    url = forms.CharField(max_length=200, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Product URL'}))

    class Meta:
        model = ProductCategory
        fields = ('name', 'url')

configuration/country/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages

from django.urls import reverse_lazy
from .models import Country
from .forms import CountryForm
from administration.userprofile.views import OrganizerRequiredMixin, OrganizerContextMixin


class CountryListView(OrganizerRequiredMixin, OrganizerContextMixin, ListView):
    model = Country
    template_name = 'configuration/country/country_list.html'
    context_object_name = 'countries'

    def get_queryset(self):
        return Country.objects.filter(organization=self.get_organization())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)              
        context['title'] = "Countries"
        context['crud'] = "Country Settings"
        return context


class CountryDetailView(OrganizerRequiredMixin, OrganizerContextMixin, DetailView):
    model = Country
    template_name = 'configuration/country/country_detail.html'
    context_object_name = 'country'


class CountryCreateView(OrganizerRequiredMixin, OrganizerContextMixin, SuccessMessageMixin, CreateView):

    model = Country
    template_name = 'configuration/country/country_create.html'
    form_class = CountryForm

    def form_valid(self, form):
        form.instance.organization = self.get_organization()
        return super().form_valid(form)

    def get_success_url(self):
        organization_slug = self.get_organization().slug
        messages.success(self.request, "Country Created.")
        return reverse_lazy('country:list', kwargs={'organization_slug': organization_slug})

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)              
        context['title'] = "Countries"
        context['crud'] = "Country Create"
        return context


class CountryUpdateView(OrganizerRequiredMixin, OrganizerContextMixin, SuccessMessageMixin, UpdateView):
    model = Country
    template_name = 'configuration/country/country_update.html'
    fields = ['name', 'code', 'is_selected']
    success_message = 'Country updated successfully'

    def get_success_url(self):
        # messages.success(self.request, "Country updated.")
        return reverse_lazy('country:list', kwargs={'organization_slug': self.get_organization().slug})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)              
        context['title'] = "Countries"
        context['crud'] = "Country Update"
        return context



class CountryDeleteView(OrganizerRequiredMixin, OrganizerContextMixin, SuccessMessageMixin, DeleteView):
    model = Country
    template_name = 'configuration/country/country_delete.html'
    success_message = "Country deleted."

    def get_success_url(self):
        # messages.success(self.request, "Country deleted.")
        return reverse_lazy('country:list', kwargs={'organization_slug': self.get_organization().slug})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)              
        context['title'] = "Countries"
        context['crud'] = "Country Delete"
        return context

configuration/currency/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.urls import reverse_lazy
from .models import Currency
from .forms import CurrencyForm
from administration.userprofile.views import OrganizerRequiredMixin, OrganizerContextMixin


class CurrencyListView(OrganizerRequiredMixin, OrganizerContextMixin, ListView):
    model = Currency
    template_name = 'configuration/currency/currency_list.html'
    context_object_name = 'currencies'

    def get_queryset(self):
        return Currency.objects.filter(organization=self.get_organization())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)              
        context['title'] = "Currencies"
        context['crud'] = "Currency Settings"
        return context

class CurrencyDetailView(OrganizerRequiredMixin, OrganizerContextMixin, DetailView):
    model = Currency
    template_name = 'configuration/currency/currency_detail.html'
    context_object_name = 'currency'

class CurrencyCreateView(OrganizerRequiredMixin, OrganizerContextMixin, CreateView):
    model = Currency
    template_name = 'configuration/currency/currency_create.html'
    form_class = CurrencyForm
    success_message = 'Currency created successfully'

    def form_valid(self, form):
        form.instance.organization = self.get_organization()
        return super().form_valid(form)
    
    def form_invalid(self, form):
        # Si el formulario es inválido, se mostrará un mensaje de error personalizado
        messages.error(self.request, "Please enter a valid code.")
        # Redirige nuevamente a la página de creación de Currency
        return super().form_invalid(form)

    def get_success_url(self):
        # messages.success(self.request, "Currency Created.")
        return reverse_lazy('currency:list', kwargs={'organization_slug': self.get_organization().slug})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)              
        context['title'] = "Currency Create"
        context['crud'] = "Currency Settings"
        return context


class CurrencyUpdateView(OrganizerRequiredMixin, OrganizerContextMixin, SuccessMessageMixin, UpdateView):
    model = Currency
    template_name = 'configuration/currency/currency_update.html'
    form_class = CurrencyForm
    success_message = 'Currency updated successfully'

    def get_success_url(self):
        # messages.success(self.request, "Currency Updated.")
        return reverse_lazy('currency:list', kwargs={'organization_slug': self.get_organization().slug })
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = self.get_object()
        context['title'] = f"{currency.code}"
        context['crud'] = "Currency Update"
        return context  


class CurrencyDeleteView(OrganizerRequiredMixin, OrganizerContextMixin, DeleteView):
    model = Currency
    template_name = 'configuration/currency/currency_delete.html'
    success_message = 'Currency deleted successfully'

    def get_success_url(self):
        # messages.success(self.request, "Currency Deleted.")
        return reverse_lazy('currency:list', kwargs={'organization_slug': self.get_organization().slug})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        currency = self.get_object()
        context['title'] = f"{currency.code}"
        context['crud'] = "Currency Delete"
        return context  

templates/configuration/product_category/category_create.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %}Create Category{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <h2>Create Category</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Create</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/configuration/product_category/category_delete.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %}Delete Category{% endblock %}

{% block content %}

    <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 mx-auto my-5">
        <div class="card">
            <h5 class="card-header">{{ category.name }}</h5>
            <div class="card-body">
                <h5 class="card-title">Are you sure you want to delete {{ category.name }}?</h5>
                <br>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/configuration/product_category/category_detail.html
{% extends "administration/core/base.html" %}

{% block title %}currencies{% endblock %}

{% block content %}

<h1 class="text-xl">{{ category.name }} <span class="badge bg-secondary">Category</span></h1>
<p>{{ category.url }} <span class="badge bg-secondary">URL</span></p>
<br><br>

<div class="row mb-3">
    <div class="col-md-8">
        <a href="{% url 'product:category-update' pk=category.pk organization_slug=organization_slug %}" class="btn btn-primary">Update</a>
        <a href="{% url 'product:category-delete' pk=category.pk organization_slug=organization_slug %}" class="btn btn-danger">Delete</a>
    </div>
</div>







{% endblock %}

templates/configuration/product_category/category_list.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %}Countries{% endblock %}

{% block content %}

    <div class="container rounded shadow-sm bg-light border border-2 p-5 my-4" style="width: 40%;">
        <ul class="list-group list-group-flush settings-items-link">            
            {% for category in categories %}
                <li class="list-group-item bg-transparent">
                    <p><strong>Name:</strong>&nbsp;&nbsp;<a href="{% url 'product:category-update' pk=category.pk organization_slug=organization_slug  %}">{{ category.name }}</a></p>
                    <p><strong>URL:</strong>&nbsp;&nbsp;<a href="{{ category.url }}" target="_blank">{{ category.url }}</a></p>             

                </li>
            {% endfor %}
        </ul>
                
        <div class="row my-4">
            <div class="btn-group">
                <a href="{% url 'product:category-create' organization_slug=organization_slug %}" class="btn btn-primary">Create</a> 
            </div>
        </div>    
    </div>

{% endblock %}

templates/configuration/product_category/category_update.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %}Update Category{% endblock %}

{% block content %}
    <div class="container rounded shadow-sm bg-light border border-2 p-5 my-4" style="width: 30%;">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <form method="post">
                    {% csrf_token %}

                    <div class="row mb-3">            
                        <div class="col-md-12">
                            <label for="id_name" class="form-label">Category Name</label>
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="row mb-3">            
                        <div class="col-md-12">
                            <label for="id_product_url" class="form-label">Category URL</label>
                            {{ form.url }}
                        </div>
                    </div>                    

                    <div class="row my-4">
                        <div class="btn-group">
                            <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                            <a href="{% url 'product:category-delete' pk=pk organization_slug=organization_slug %}" class="btn btn-danger">Delete</a>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </div>
                  
                </form>
            </div>
        </div>
    </div>
{% endblock %}