administration/core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import CustomLoginView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login-home'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

administration/organization/urls.py
from django.urls import path

# from administration.organization.views import upload_file_view
from .views import ImageUploadView, MediaLibraryView

app_name = 'organization'

urlpatterns = [
        path('upload/', ImageUploadView.as_view(), name='upload-file'),
        path('library/', MediaLibraryView.as_view(), name='media-library'),
]

operation/client/urls.py
from django.urls import path
from .views import HomeClientView, ClientListView, ClientDetailView


app_name = 'client'

urlpatterns = [
    path('list/', HomeClientView.as_view(), name='client-list'),
    path('clients_json/', ClientListView.as_view(), name='client-json'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    # path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),   

]

operation/company/urls.py
from django.urls import path
from .views import CompanyListView, CompanyHomeView, CompanyDetailView

app_name = 'company'

urlpatterns = [
    path('list/', CompanyHomeView.as_view(), name='company-list'),
    path('companies_json/', CompanyListView.as_view(), name='company-json'),
    path('<int:pk>/', CompanyDetailView.as_view(), name='company-detail'),
]

operation/deal/urls.py
from django.urls import path
from .views import HomeDealView, DealListView, DealDetailView, DealUpdateView, DealDeleteView, DealHomeTaskView, DealTaskListView, DealTaskDetailView, DealTaskUpdateView, DealTaskDeleteView, DealTaskCreateView

app_name = 'deal'

urlpatterns = [
    path('list/', HomeDealView.as_view(), name='list'),
    path('deals_json/', DealListView.as_view(), name='deal-json'),
    # path('create/', DealCreateView.as_view(), name='create'),
    path('<int:pk>/', DealDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', DealUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', DealDeleteView.as_view(), name='delete'),

    path('task/list/', DealHomeTaskView.as_view(), name='task-list'),
    path('tasks_json/', DealTaskListView.as_view(), name='task-json'),
    path('<int:deal_pk>/task/create/', DealTaskCreateView.as_view(), name='task-create'),
    path('task/<int:pk>/', DealTaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update/', DealTaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', DealTaskDeleteView.as_view(), name='task-delete'),
]

operation/lead/urls.py
from django.urls import path
from .views import HomeLeadView, LeadListView, LeadCreateView, LeadUpdateView, LeadDetailView, LeadDeleteView, LeadTaskCreateView, LeadHomeTaskView, LeadTaskListView, LeadTaskDetailView, LeadTaskDeleteView, LeadTaskUpdateView, convert_lead_to_deal

app_name = 'lead'

urlpatterns = [
    path('list/', HomeLeadView.as_view(), name='list'),
    path('leads_json/', LeadListView.as_view(), name='lead-json'),
    path('create/', LeadCreateView.as_view(), name='create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='delete'),
    path('converted_to_deal/<int:pk>/', convert_lead_to_deal, name='converted-to-deal'),


    path('task/list/', LeadHomeTaskView.as_view(), name='task-list'),
    path('tasks_json/', LeadTaskListView.as_view(), name='task-json'),
    path('<int:lead_pk>/task/create/', LeadTaskCreateView.as_view(), name='task-create'),
    path('task/<int:pk>/', LeadTaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update/', LeadTaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', LeadTaskDeleteView.as_view(), name='task-delete'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('administration.core.urls')),
    path('<slug:organization_slug>/media/', include('administration.organization.urls')),
    path('', include('operation.dashboard.urls')),
    path('<slug:organization_slug>/dashboard/', include('operation.dashboard.urls')),

    path('<slug:organization_slug>/configuration/country/', include('configuration.country.urls')),
    path('<slug:organization_slug>/configuration/currency/', include('configuration.currency.urls')),

    path('<slug:organization_slug>/lead/', include('operation.lead.urls')),
    path('<slug:organization_slug>/deal/', include('operation.deal.urls')),
    path('<slug:organization_slug>/contact/', include('operation.contact.urls')),
    path('<slug:organization_slug>/company/', include('operation.company.urls')),
    path('<slug:organization_slug>/client/', include('operation.client.urls')),
    path('<slug:organization_slug>/product/', include('configuration.product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administration/core/models.py
from django.db import models

# Create your models here.

administration/organization/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.core.validators import RegexValidator
from django.utils.text import slugify


from administration.userprofile.models import User

def get_sentinel_user():
    user, created = User.objects.get_or_create(username="deleted")
    if created:
        user.set_unusable_password()
        user.save()
    return user

class Organization(models.Model):
    name = models.CharField(max_length=100, unique=True, validators=[
        RegexValidator(
            regex='^[a-zA-Z0-9 ]*$',  # Permite letras, números y espacios
            message='El nombre solo puede contener letras, números y espacios.'
        )
    ])
    slug = models.SlugField(unique=True, blank=True)  # Campo slug añadido
    created_by = models.ForeignKey(
        User, related_name='created_organizations', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    # Convierte el nombre a slug antes de guardar
    def save(self, *args, **kwargs):
        # Genera el slug a partir del nombre si no existe
        if not self.slug:
            self.slug = slugify(self.name)
        super(Organization, self).save(*args, **kwargs)

    class Meta:
        ordering = ('name',)

    #  Para que el nombre de la organización esté en formato de título.
    def clean(self):
        super().clean()
        self.name = self.name.title()

    def __str__(self):
        return self.name

@receiver(pre_delete, sender=Organization)
def delete_related_profiles(sender, instance, **kwargs):
    organizer = getattr(instance, 'organizer', None)
    agents = instance.agent.all()
    if organizer:
        organizer.delete()
    for agent in agents:
        agent.delete()


# Archivo se guardará en MEDIA_ROOT/organizations/<id>/<filename>
def organization_directory_path(instance, filename):
    return f'organizations/{instance.organization.id}/{filename}'

class OrganizationMedia(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    image = models.ImageField(upload_to=organization_directory_path, height_field='image_height', width_field='image_width')
    image_height = models.PositiveIntegerField(editable=False, null=True)
    image_width = models.PositiveIntegerField(editable=False, null=True)
    image_size = models.PositiveIntegerField(editable=False, null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_media', on_delete=models.SET(get_sentinel_user))

    def __str__(self):
        return f"{self.organization.name} Media"

administration/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from administration.organization.models import Organization

class Organizer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.OneToOneField(
        Organization, null=True, on_delete=models.SET_NULL,  related_name='organizer', error_messages={
            'unique_together': "Este usuario ya es organizer de otra organización.",
        })
    created_by = models.ForeignKey(
        User, related_name='created_organizer', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('user',)

    def __str__(self):
        return self.user.username


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(
        Organization,
        null=True,
        on_delete=models.SET_NULL,
        related_name='agent',
        error_messages={
            'unique_together': "Este usuario ya es agente de otra organización.",
        }
    )
    created_by = models.ForeignKey(
        User, related_name='created_agent', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ('user',)

    def __str__(self):
        return self.user.username

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, blank=True, null=True)

# Guarda en Profile al User creado
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    Profile.objects.get_or_create(user=instance)

administration/organization/forms.py
from django import forms
from .models import OrganizationMedia
from django.core.exceptions import ValidationError


class OrganizationMediaForm(forms.ModelForm):
    class Meta:
        model = OrganizationMedia
        fields = ['image']

    def clean_image(self):
        image = self.cleaned_data.get('image', False)
        if image:
            if image.size > 1 * 1024 * 1024:  # 1MB limit
                raise ValidationError("El tamaño del archivo es demasiado grande (máximo 1MB).")
            self.instance.image_size = image.size
        return image
    

administration/core/views.py
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy

class CustomLoginView(LoginView):
    def form_valid(self, form):
        response = super().form_valid(form)
        success_url = reverse_lazy('dashboard-home')
        if hasattr(self.request.user, 'organizer'):
            organization_slug = self.request.user.organizer.organization.slug        
            success_url = reverse_lazy(
                'dashboard-home', kwargs={'organization_slug': organization_slug})
            messages.success(self.request, 'You have been logged in successfully as an Organizer.')
        elif hasattr(self.request.user, 'agent'):
            organization_slug = self.request.user.agent.organization.slug     
            success_url = reverse_lazy(
                'dashboard-home', kwargs={'organization_slug': organization_slug})
            messages.success(self.request, 'You have been logged in successfully as an Agent.')
        else:            
            messages.success(self.request, 'You have been logged in successfully.')
        return redirect(success_url)

administration/organization/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404


from administration.userprofile.views import OrganizerContextMixin, OrganizerRequiredMixin
from administration.organization.models import Organization, OrganizationMedia
from .forms import OrganizationMediaForm
  

class ImageUploadView(LoginRequiredMixin, OrganizerRequiredMixin, OrganizerContextMixin, FormView):
    template_name = 'administration/organization/upload_media.html'
    form_class = OrganizationMediaForm
    validation_error_handled = False
    # success_url = reverse_lazy('some-success-url')  # Cambia esto a tu URL de éxito

    def form_valid(self, form):
        organizer = self.request.user.organizer
        organization_media = form.save(commit=False)
        organization_media.organization = self.get_organization()
        organization_media.created_by = organizer.user
        organization_media.save()
        messages.success(self.request, "Imagen subida correctamente")
        return super().form_valid(form)

    def form_invalid(self, form):
        # Manejar lo que sucede cuando el formulario no es válido
        return super().form_invalid(form)
    
    def get_success_url(self):  
        return reverse_lazy('lead:list', kwargs={'organization_slug': self.get_organization().slug})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context.update({'organization_slug': self.get_organization()})
        context['titulo'] = 'Subir Imagen'
        return context


class MediaLibraryView(LoginRequiredMixin, OrganizerRequiredMixin, OrganizerContextMixin, ListView):
    model = OrganizationMedia
    template_name = 'administration/organization/media_library.html'
    context_object_name = 'media_list'

    def get_queryset(self):
        # organization_id = self.kwargs['organization_id']
        # print('organization_id  ', organization_id)
        organization_slug = self.kwargs['organization_slug']
        # organization = get_object_or_404(Organization, name=organization_slug)
        organization = get_object_or_404(Organization, slug=organization_slug)
        return OrganizationMedia.objects.filter(organization=organization)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context.update({'organization_slug': self.get_organization()})
        context['titulo'] = 'Media Library'
        return context
    

administration/userprofile/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from .models import Organizer, Agent

''' 
/************
MIXINS
/************
'''

class OrganizerRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        user_is_organizer = Organizer.objects.filter(
            user=self.request.user, user__is_active=True).exists()
        return user_is_organizer

class OrganizerContextMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['organization_name'] = self.get_organization()
        context['organization'] = self.get_organization()
        return context

    def get_organization(self):
        return self.request.user.organizer.organization    

class AgentRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        user_is_agent = Agent.objects.filter(
            user=self.request.user, user__is_active=True).exists()
        return user_is_agent
    
class AgentContextMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['organization_name'] = self.get_organization()
        context['organization'] = self.get_organization()
        return context

    def get_organization(self):
        return self.request.user.agent.organization

    

templates/administration/core/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titulo }}</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    {% block styles %}{% endblock %}
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/be_crm.css' %}">

</head>

<body>  

    <div class="navbar bg-dark flex-md-nowrap p-0 shadow sticky-top fixed-top" data-bs-theme="dark">      
        {% if request.user.is_authenticated and request.user.agent %}
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" href="{% url 'dashboard-home' organization_slug=organization_slug %}" > 
                <span>{{ organization_name|default:"Nombre de CRM predeterminado" }}</span>
            </a>
        {% else %}
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6 text-white" > 
                <span>{{ "CRM" }}</span>
            </a>           
        {% endif %}           
    </div>

    {% include 'administration/core/navbar.html' %}

    <div class="container mt-2">
        <br>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>Success:</strong> {{ message }}.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% elif message.tags == 'warning' %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <strong>Warning:</strong> {{ message }}.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div> 
                {% elif message.tags == 'error' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Danger:</strong> {{ message }}.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>

    <div class="container mt-4">
        {% block content %}{% endblock %}
    </div>

    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.7.0.js"></script>
    <!-- URL base -->
    <script>const BASE_URL = "{{ request.scheme }}://{{ request.get_host }}";</script>

    {% block scripts %}
    {% endblock %}
</body>

</html>

templates/administration/core/navbar.html
<nav class="navbar navbar-expand-sm bg-light navbar-light shadow sticky-top">
    <h1 class="title h3 align-middle m-0 text-nowrap ms-3">{{ title|default:"My CRM" }} <span class="badge bg-black badge-navbar">{{ crud }}</span></h1><!-- Muestra el título de la sección o un valor por defecto -->

    <div class="container-fluid justify-content-lg-end">          
        <!-- Boton offcanvas -->
        {% if request.user.is_authenticated and request.user.agent %}
            <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            </button>   
        {% else %}
            <span class="ps-4">&nbsp;</span>
        {% endif %}        
        <!-- Boton offcanvas -->           
    </div>

</nav>

<div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
        {% if not request.user.is_authenticated %}
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Blasting Experts</h5>
        {% else %}      
            {% if request.user.organizer %}
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                    {{ request.user.organizer.organization }}
                </h5>
            {% endif %}  
        {% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">
      {% if request.user.is_authenticated and request.user.agent %}
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3 mx-4 mb-4">                  
                <li class="nav-item">
                    <a class="nav-link" href="#">Logged in as: <span class="badge bg-secondary fs-6">{{ request.user.username }}</span></a>
                </li>  

                <li class="nav-item offcanvas-logout">
                    <a class="link-offset-2" href="{% url 'logout' %}">Logout</a>
                </li>                                    
            </ul>
            <hr class="mt-3">

            {% if request.user.organizer %}
                <h5 class="offcanvas-title my-4 opacity-50">
                    Configuration
                </h5>

                <ul class="navbar-nav mx-4 offcanvas-link">                                    
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                        href="{% url 'country:list' organization_slug=organization_slug %}">Countries</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                            href="{% url 'product:list' organization_slug=organization_slug %}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                            href="{% url 'product:category-list' organization_slug=organization_slug %}">Product Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page"
                            href="{% url 'currency:list' organization_slug=organization_slug %}">Currency</a>
                    </li>

                    <li class="nav-item">  
                        <a class="nav-link" aria-current="page"
                            href="{% url 'organization:upload-file' organization_slug=organization_slug %}">Images</a>                                     
                    </li>
                    <li class="nav-item">  
                        <a class="nav-link" aria-current="page"
                            href="{% url 'organization:media-library' organization_slug=organization_slug %}">Media Library</a>                                     
                    </li>
                   
                </ul>
            {% endif %}  
        {% endif %}                           
    </div>
</div>

templates/administration/core/navbar1.html
<nav class="navbar navbar-expand-sm bg-light navbar-light sticky-top">

    <!-- Boton offcanvas -->
    {% if request.user.is_authenticated and request.user.agent %}
        <button class="btn" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon link-underline-opacity-25 link-underline-opacity-100-hover"></span>
        </button>   
    {% else %}
        <span class="ps-4">&nbsp;</span>
    <!-- Boton offcanvas -->   
    {% endif %}        

    <h1 class="title h3 align-middle m-0 text-nowrap">{{ title|default:"My CRM" }} <span class="badge bg-black badge-navbar">{{ crud }}</span></h1><!-- Muestra el título de la sección o un valor por defecto -->

    <div class="container-fluid justify-content-lg-end">              
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start dropstart">
            <div class="dropdown">            
                <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                
                <ul class="dropdown-menu text-small">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Logged in as: {{ request.user.username }}</a>
                    </li>                            
                    {% if request.user.organizer %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Configuration
                            </a>
                                <ul class="dropdown-menu">                                    
                                    <li>
                                        <a class="dropdown-item" aria-current="page"
                                        href="{% url 'country:list' organization_slug=organization_slug %}">Countries</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" aria-current="page"
                                            href="{% url 'product:list' organization_slug=organization_slug %}">Products</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" aria-current="page"
                                            href="{% url 'product:category-list' organization_slug=organization_slug %}">Product Categories</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" aria-current="page"
                                            href="{% url 'currency:list' organization_slug=organization_slug %}">Currency</a>
                                    </li>
        
                                    <li>  
                                        <a class="dropdown-item" aria-current="page"
                                            href="{% url 'organization:upload-file' organization_slug=organization_slug %}">Images</a>                                     
                                    </li>
                                    <li>  
                                        <a class="dropdown-item" aria-current="page"
                                            href="{% url 'organization:media-library' organization_slug=organization_slug %}">Media Library</a>                                     
                                    </li>
                                    <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                                    </li>
                                </ul>
                            </li>
                    {% endif %}  
                    <li><a class="dropdown-item" href="#">New project...</a></li>
                    <li><a class="dropdown-item" href="#">Settings</a></li>
                    <li><a class="dropdown-item" href="#">Profile</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Sign out</a></li>
                </ul>            
            </div>        
        </div>
    </div>
</nav>


<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
    <div class="offcanvas-header">
        {% if not request.user.is_authenticated %}
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Blasting Experts</h5>
        {% else %}      
            {% if request.user.organizer or request.user.agent %}
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                    {% if request.user.organizer %}
                    {{ request.user.organizer.organization }}
                    {% elif request.user.agent %}
                    {{ request.user.agent.organization }}
                    {% endif %}                    
                </h5>
            {% else %}
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Blasting Experts Inc.</h5>
            {% endif %}  
        {% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">
      {% if request.user.is_authenticated and request.user.agent %}
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">                    
                <li><a class="nav-link" href="{% url 'lead:list' organization_slug=organization_slug %}"><i class="fas fas fas fa-lightbulb"></i> Leads</a></li>
                <li><a class="nav-link" href="{% url 'lead:task-list' organization_slug=organization_slug %}"><i class="fas fas fas fa-tasks"></i> Lead Tasks</a></li>
                <li><a class="nav-link" href="{% url 'contact:contact-list' organization_slug=organization_slug %}"><i class="fas fas fa-address-book"></i> Contacs</a></li>    
                <hr>            
                <li><a class="nav-link" href="{% url 'deal:list' organization_slug=organization_slug %}"><i class="fas fa-handshake"></i> Deals</a></li>
                <li><a class="nav-link" href="{% url 'deal:task-list' organization_slug=organization_slug %}"><i class="fas fas fas fa-tasks"></i> Deal Tasks</a></li>
                <li><a class="nav-link" href="{% url 'client:client-list' organization_slug=organization_slug %}"><i class="fas fas fas fa-id-badge"></i> Clients</a></li>
                <li><a class="nav-link" href="{% url 'company:company-list' organization_slug=organization_slug %}"><i class="fas fas fas fa-building"></i> Companies</a></li>
                </li>    
            </ul>
        {% endif %}                           
    </div>
</div>